### ISSUE TITLE
Full site testing

### ISSUE THREAD

**Issue by JackOfSpades42** [adpangelinan/CS340Group43Project#5]
Leave a comment once everything has been tested for each page.

**Comment by JackOfSpades42** [comment]
Delete and update work

**Comment by JackOfSpades42** [comment]
Blank fields give 500 error

**Comment by JackOfSpades42** [comment]
Adding/deleting people from powers and groups works

**Comment by adpangelinan** [comment]
Got error on "Name' undefined when trying to add powers to characters (issue in viewPow.js:39:35)
